In [2]:
import torch

In [3]:
# create tensor
x = torch.arange(12, dtype=torch.float64)
x

tensor([ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11.],
       dtype=torch.float64)

In [5]:
print(x.shape)
print(x.size())

torch.Size([12])
torch.Size([12])


In [6]:
x = x.reshape((3, 4))
x

tensor([[ 0.,  1.,  2.,  3.],
        [ 4.,  5.,  6.,  7.],
        [ 8.,  9., 10., 11.]], dtype=torch.float64)

In [9]:
x = x.reshape(2,-1)
x

tensor([[ 0.,  1.,  2.,  3.,  4.,  5.],
        [ 6.,  7.,  8.,  9., 10., 11.]], dtype=torch.float64)

In [10]:
x = x.reshape((2, 2, -1))
x

tensor([[[ 0.,  1.,  2.],
         [ 3.,  4.,  5.]],

        [[ 6.,  7.,  8.],
         [ 9., 10., 11.]]], dtype=torch.float64)

In [11]:
x = x.reshape(2, 3, -1)
x

tensor([[[ 0.,  1.],
         [ 2.,  3.],
         [ 4.,  5.]],

        [[ 6.,  7.],
         [ 8.,  9.],
         [10., 11.]]], dtype=torch.float64)

In [12]:
torch.zeros(2,3,4)
torch.ones(2,3,4)

tensor([[[1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.]],

        [[1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.]]])

# Optical Character Recognition

In [ ]:
%matplotlib inline
import tqdm
import numpy as np
import matplotlib.pyplot as plt
from IPython import display # ???
display.set_matplotlib_formats('svg') # ???

